---
- name: Create dynamic hosts
  hosts: localhost
  tasks:
    - name: Dynamic ip for VM
      add_host:
        hostname: '{{ ext_vm_ip1 }}'
        groups:
        - target 
        
- name: Set up the NFS services
  hosts: target
  #hosts: '{{ ext_vm_ip1 }}'
  roles:
    - 01-nfs