---
- name: set vm hostname
  template:
    src: hostname.j2
    dest: /etc/HOSTNAME
    mode: '0644'
  register: vm_hostname_result

- name: set vm dns configuration
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: '0644'
  register: vm_dns_result

- name: set vm IP and GW
  template:
    src: rc.inet1.conf.j2
    dest: /etc/rc.d/rc.inet1.conf
    mode: '0644'
  register: vm_ip_and_gw_result

#- name: shutdown vm
#  shell: |
#    shutdown -h now
#  register: vm_shutdown_result

#- name: replace vm network
#  shell: |
#    govc vm.network.change -vm {{ vm_name }} -net {{ vm_network }} ethernet-0 
#  register: vm_network_replace_result

##- debug:
##    msg: "{{ vm_hostname_result }}"
##- debug:
##    msg: "{{ vm_dns_result }}"
##- debug:
##    msg: "{{ vm_ip_and_gw_result }}"
##- debug:
##    msg: "{{ vm_shutdown_result }}"

#- debug:
#    msg: "{{ vm_network_replace_result }}"
# other way to do 'debug msg' 
#- debug: msg="{{ vm_shutdown_result }}"
