---
- name: Create dynamic hosts
  hosts: localhost
  tasks:
    - name: Dynamic ip for VM
      add_host:
        hostname: '{{ ext_vm_ip1 }}'
        groups:
        - target 
        
- name: Set up the GW/FW/Router services
  # hosts: "{{ lookup('env','HOSTS') }}"
  hosts: target 
  roles:
    - 01-mirror

- name: Detach the ISO from VM
  hosts: vcenter
  roles:
    - 02-removeiso