---
- name: include vars
  include_vars: "{{ playbook_dir }}/vars.yaml"
  
- name: Create a VM from a template
  vmware_guest:
    hostname: '{{ vc_hostname }}'
    username: '{{ vc_username }}'
    password: '{{ vc_password }}'
    validate_certs: False
    datacenter: "LAB"
    cluster: "Cluster_LAB"
    resource_pool: '{{ vc_resource_pool }}'
    folder: '{{ vc_folder }}'
    template: '{{ vc_template }}'
    name: '{{ vm_name }}'
    state: poweredon
    wait_for_ip_address: yes
    wait_for_ip_address_timeout: 600 
  delegate_to: localhost
  register: vm_info
#  until: vm_info.instance.hw_power_status == 'poweredOn'
#  until: vm_info.hw_power_status == 'poweredOn'
  retries: 10
  delay: 5
#- debug: msg='{{ vm_info }}'
- debug: msg='{{ vm_info.instance.ipv4 }}'
