---
- name: include vars
  include_vars: "{{ playbook_dir }}/vars.yaml"

- name: Clone VM with 1 nic 
  include_tasks: clone-vm-with-1-nics.yaml 
  when: vm_network2 is not defined 

- name: Clone VM with 2 nics 
  include_tasks: clone-vm-with-2-nics.yaml 
  when: vm_network2 is defined 
